### ISSUE TITLE
Cannot find module './types/cqlTypes'

### ISSUE THREAD

**Issue by dfaust** [lawrencekgrant/vscode-cql#3]
Activating the extension fails with the following errors (taken from the developer tools console):

vscode version: 1.9.1
vscode-cql version: 0.7.1

```
Unknown injections for grammar <source.cql>: Error: Unknown injections for grammar <source.cql>
    at Registry._loadGrammar (/usr/share/code/resources/app/node_modules/vscode-textmate/release/main.js:2929:30)
    at Registry.loadGrammarWithEmbeddedLanguages (/usr/share/code/resources/app/node_modules/vscode-textmate/release/main.js:2878:14)
    at file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:137:7819
    at new n.Class.derive._oncancel (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:32:19517)
    at e._createGrammar (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:137:7769)
    at e.registerDefinition (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:137:8011)
    at file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:137:5415
    at e.invoke (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:26950)
    at e.fire (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:30:30440)
    at t.e._getOrCreateMode (file:////usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:69:26914)
[Extension Host] Activating extension `LawrenceGrant.cql` failed: Cannot find module './types/cqlTypes'.
[Extension Host] Activating extension `LawrenceGrant.cql` failed:  Cannot find module './types/cqlTypes'
[Extension Host] Here is the error stack:  Error: Cannot find module './types/cqlTypes'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.V.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:14:30928)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/daniel/.vscode/extensions/LawrenceGrant.cql-0.7.1/out/src/cqlCassandraScanner.js:5:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.V.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:14:30928)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/daniel/.vscode/extensions/LawrenceGrant.cql-0.7.1/out/src/extension.js:9:29)
    at Module._compile (module.js:556:32)
Activating extension `LawrenceGrant.cql` failed: Cannot find module './types/cqlTypes'.
```

**Comment by jacobgardner** [comment]
This is due to linux having case-sensitive filesystems.  There were a few places I had to rename the files to match the cases in the files.   I just submitted a PR to fix this issue.

**Comment by lawrencekgrant** [comment]
Hey guys, I was going through some medical issues. So, I'm BAAACK! I will test this PR and update the product ASAP.
