### ISSUE TITLE
command 'cql.execute' not found for VSCode Linux Mint

### ISSUE THREAD

**Issue by hofucai** [lawrencekgrant/vscode-cql#7]
I'm new to Cassandra and found your VS code plug-in.
Tried executing some sql from vs and received the message:

"command 'cql.execute' not found"

**Comment by Vinno97** [comment]
I am having the exact same problem on `Ubuntu 16.04` and in both VS Code `1.17.0` and `1.16.x` (the last one before 1.17.0)

**Comment by alidehghan** [comment]
I think your extension is not working at all

**Comment by sonikro** [comment]
Same Issue. VSCODE   Version 1.20.1

**Comment by chiluap** [comment]
same here on:
System:
`DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.3
DISTRIB_CODENAME=sylvia
DISTRIB_DESCRIPTION="Linux Mint 18.3 Sylvia"`

VS-Code:
`Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:34:44.222Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64`

Any progress on the issue?
Can I output some log for resolution?

**Comment by chiluap** [comment]
Maybe this StackTrace will help:


console.ts:136 [Extension Host] Here is the error stack:  Error: Cannot find module './keySpace'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/usr/share/code/resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/home/me/.vscode/extensions/LawrenceGrant.cql-0.8.7/out/src/types/cqlItemTypes.js:3:20)
	at Object.<anonymous> (/home/me/.vscode/extensions/LawrenceGrant.cql-0.8.7/out/src/types/cqlItemTypes.js:10:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/usr/share/code/resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/home/me/.vscode/extensions/LawrenceGrant.cql-0.8.7/out/src/cqlCassandraScanner.js:6:24)
	at Object.<anonymous> (/home/me/.vscode/extensions/LawrenceGrant.cql-0.8.7/out/src/cqlCassandraScanner.js:222:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/usr/share/code/resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/home/me/.vscode/extensions/LawrenceGrant.cql-0.8.7/out/src/extension.js:10:29)
	at Object.<anonymous> (/home/me/.vscode/extensions/LawrenceGrant.cql-0.8.7/out/src/extension.js:43:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/usr/share/code/resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Function.i [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:30:770)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:676:131
	at t._doActivateExtension (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:676:243)
	at t._activateExtension (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:675:161)
	at Object.actualActivateExtension (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:673:282)
	at e._activateExtension (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:417:920)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:417:539
	at Array.map (native)
	at e._activateExtensions (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:417:514)
	at e.activateByEvent (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:416:14)
	at t.activateByEvent (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:673:646)
	at t.$activateByEvent (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:677:822)
	at e._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:560:395)
	at e._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:560:113)
	at e._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:559:237)
	at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:559:6)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:558:75
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:560:929
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:88:30
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:89:344)
	at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:143:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
extensionService.ts:848 Activating extension 'LawrenceGrant.cql' failed: Cannot find module './keySpace'.

**Comment by chiluap** [comment]
OK, Ich changed the file-names in the types folder to CamelCase and it worked.
This seeems to be already fixed in the repo but not in the VSC plugin store.
Only thing missing for me now would be auth as suggested in #6.
Thank you for your work.

c.

**Comment by lawrencekgrant** [comment]
Thank you everyone for reporting the issue. Thanks @chiluap for the recommendation and information. I am currently looking into solving this issue.
