### ISSUE TITLE
Execute CQL with multiple statements

### ISSUE THREAD

**Issue by DanBehrendt** [lawrencekgrant/vscode-cql#8]
Shift + F5 CQL execution has issue with multiple statements in same .CQL file.  Is this not a supported scenario?  Thanks, Dan.

For example:

**Succeeds**
DROP KEYSPACE foo;

**Fails**
DROP KEYSPACE foo;
DROP KEYSPACE bar;
DROP KEYSPACE baz;

**With the following**
{ Error: line 2:0 mismatched input 'DROP' expecting EOF (DROP KEYSPACE foo;
[DROP]...)
	at ResponseError.DriverError (C:\Users\dan\.vscode\extensions\LawrenceGrant.cql-0.8.7
ode_modules\cassandra-driver\lib\errors.js:14:19)
	at new ResponseError (C:\Users\dan\.vscode\extensions\LawrenceGrant.cql-0.8.7
ode_modules\cassandra-driver\lib\errors.js:51:24)
	at FrameReader.readError (C:\Users\dan\.vscode\extensions\LawrenceGrant.cql-0.8.7
ode_modules\cassandra-driver\lib\readers.js:316:13)
	at Parser.parseBody (C:\Users\dan\.vscode\extensions\LawrenceGrant.cql-0.8.7
ode_modules\cassandra-driver\lib\streams.js:182:66)
	at Parser._transform (C:\Users\dan\.vscode\extensions\LawrenceGrant.cql-0.8.7
ode_modules\cassandra-driver\lib\streams.js:137:10)
	at Parser.Transform._read (_stream_transform.js:167:10)
	at Parser.Transform._write (_stream_transform.js:155:12)
	at doWrite (_stream_writable.js:329:12)
	at writeOrBuffer (_stream_writable.js:315:5)
	at Parser.Writable.write (_stream_writable.js:241:11)
	at Protocol.ondata (_stream_readable.js:557:20)
  name: 'ResponseError',
  stack: 'Error: line 2:0 mismatched input \'DROP\' expecting EOF (DROP KEYSPACE foo;\r[DROP]...)
\tat ResponseError.DriverError

**Comment by Diom** [comment]
This is something I have seen too, and it is really diminishing an otherwise excellent extension.
